name: Virtualbox
on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/virtualbox.yml
    - actions/packer-virtualbox/Dockerfile
    - virtualbox.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: virtualbox - packer validate
        uses: docker://hashicorp/packer:1.4.3
        with:
          args: validate virtualbox.json
      - name: virtualbox - packer build
        run: |
          sudo apt-get update
          sudo apt-get install -y git bash openssl curl zip 

          curl -SL https://releases.hashicorp.com/packer/1.4.2/packer_1.4.2_linux_amd64.zip -o packer_1.4.2_linux_amd64.zip
          unzip packer_1.4.2_linux_amd64.zip
          ./packer build virtualbox.json
      # - name: virtualbox - packer build
      #   uses: ./actions/packer-virtualbox
      #   with:
      #     args: build virtualbox.json